CREATE TABLE FOOD_PLACE
(
    ID int PRIMARY KEY AUTO_INCREMENT,
    ID_CUSTOMER VARCHAR(25),
    PHOTO_URL VARCHAR(500),
    DISTRICT VARCHAR(100),
    ADDRESS VARCHAR(300) NOT NULL,
    LATITUDE LONG NOT NULL,
    LONGITUDE LONG NOT NULL,
    NAME VARCHAR(100) NOT NULL
)