package com.donalola.foodmenu.infraestructure.dao.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.donalola.commons.dynamodb.util.DynamoDBConverter;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@NoArgsConstructor
@AllArgsConstructor
@Data
@DynamoDBTable(tableName = "FOOD_MENU")
public class FoodMenuDynamoEntity {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "foodPlaceId")
    private String foodPlaceId;

    @DynamoDBAttribute(attributeName = "foodPlaceName")
    private String foodPlaceName;

    @DynamoDBTypeConverted(converter = DynamoDBConverter.LocalDateTimeConverter.class)
    @DynamoDBAttribute(attributeName = "createdDatetime")
    private LocalDateTime createdDatetime;

    @DynamoDBTypeConverted(converter = DynamoDBConverter.LocalDateTimeConverter.class)
    @DynamoDBAttribute(attributeName = "finishedDatetime")
    private LocalDateTime finishedDatetime;

    @DynamoDBAttribute(attributeName = "name")
    private String name;

    @DynamoDBAttribute(attributeName = "status")
    private String status;
}
