package com.donalola.foodmenu.infraestructure.dao.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.donalola.commons.dynamodb.util.DynamoDBConverter;
import com.donalola.foodmenu.FoodMenu;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.Optional;

@NoArgsConstructor
@AllArgsConstructor
@Data
@DynamoDBTable(tableName = "FOOD_MENU")
public class FoodMenuDynamoEntity {

    public FoodMenuDynamoEntity(final FoodMenu foodMenu) {
        if (Optional.ofNullable(foodMenu.getId()).isPresent()) {
            this.id = foodMenu.getId();
        }
        this.idFoodPlace = foodMenu.getIdFoodPlace();
        this.menuDate = LocalDateTime.now();
        if (Optional.ofNullable(foodMenu.getLocalDateTime()).isPresent()) {
            this.menuDate = foodMenu.getLocalDateTime();
        }
        this.name = foodMenu.getName();
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute(attributeName = "idFoodPlace")
    private String idFoodPlace;

    @DynamoDBAttribute(attributeName = "foodPlaceName")
    private String foodPlaceName;

    @DynamoDBTypeConverted(converter = DynamoDBConverter.LocalDateTimeConverter.class)
    @DynamoDBAttribute(attributeName = "menuDate")
    private LocalDateTime menuDate;

    @DynamoDBAttribute(attributeName = "name")
    private String name;
}
